[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
]

[monitors.placement]
"Acer".top_center_of = "Sony"

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

# [scratchpads.stb]
# animation = "fromBottom"
# command = "kitty --class kitty-stb sstb"
# class = "kitty-stb"
# lazy = true
# size = "75% 45%"

# [scratchpads.stb-logs]
# animation = "fromTop"
# command = "kitty --class kitty-stb-logs stbLog"
# class = "kitty-stb-logs"
# lazy = true
# size = "75% 40%"

[scratchpads.term]
name = "dropterm-rule"
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "88% 40%"
# Ensure it hides when clicking away
unfocus = "hide"
# Optional: margin from the top to account for Waybar
margin = 10

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"
